### ISSUE TITLE
Why are the constructors of the Monoidal containers hidden?

### ISSUE THREAD

**Issue by louispan** [bgamari/monoidal-containers#12]
It doesn't provide any additional safety since the construction can still be accessed by using the Wrapped or Newtype instances, so is there a reason to hide the constructors?

I would prefer it if there were `getMonoidal` handy accessors as well. I'd be happy to provide a pull request if you agree.

**Comment by bgamari** [comment]
No particular reason; I would gladly accept a pull request exposing them with selectors.

**Comment by bgamari** [comment]
Fixed in a364a3a9870d46822dbeb4dc342f853caca14805.
