### ISSUE TITLE
ToJSON / FromJSON instances

### ISSUE THREAD

**Issue by reactormonk** [bgamari/monoidal-containers#21]
Would add dependencies, but nice to have.

**Comment by bgamari** [comment]
I'm not sure that I would want to add an `aeson` dependency for this.

**Comment by reactormonk** [comment]
Your pick, otherwise close the PR.

**Comment by 3noch** [comment]
These were added in #26.

**Comment by 3noch** [comment]
@bgamari Oops I referenced the wrong PR: https://github.com/bgamari/monoidal-containers/pull/25/files#diff-fed208219bcd4d0b66152ea0e3598e9aR157

**Comment by ali-abrar** [comment]
https://github.com/bgamari/monoidal-containers/blob/master/src/Data/Map/Monoidal.hs#L159
