### ISSUE TITLE
Relax hashable constraint

### ISSUE THREAD

**Issue by k-bx** [bgamari/monoidal-containers#38]
I just checked, monoidal-containers builds fine with `hashable-1.3.0.0`. Please make a revision on Hachage and an edit in cabal file.

Btw, I am happy to become a co-maintainer and do that myself. Thank you!

**Comment by k-bx** [comment]
I suspect semigroups would also build ok but please check https://github.com/commercialhaskell/stackage/issues/4530#issuecomment-491317462

**Comment by ali-abrar** [comment]
Could you make a PR for this so it goes through CI?

**Comment by ali-abrar** [comment]
This'll be fixed once #48 is merged.
