### ISSUE TITLE
fromList is unintuitive

### ISSUE THREAD

**Issue by 5outh** [bgamari/monoidal-containers#43]
Hey there - 

The `fromList` implementation for `Data.Map.Monoidal.Map` is a little unintuitive. I spent a while debugging this issue and wonder if the implementation should be changed.

```haskell
Prelude> import qualified Data.Map.Monoidal as MonoidalMap
Prelude MonoidalMap> MonoidalMap.fromList [(1, ['a']), (1, ['b'])]
MonoidalMap {getMonoidalMap = fromList [(1,"b")]}
# I expect `MonoidalMap {getMonoidalMap = fromList [(1,"ab")]}` here
```

In other words, `fromList` should convert each element in the list to a singleton and mash them together with `mconcat` instead of preferring the last element.

### Edit

An `Applicative` (or other singleton-producing typeclass) constraint would have to be placed on `f` in this case, which might be a deal-breaker that I hadn't considered. Still curious to hear your thoughts.

**Comment by ali-abrar** [comment]
#41 should resolve this, once merged.
