### ISSUE TITLE
Consider dropping support for GHC 7

### ISSUE THREAD

**Issue by fumieval** [bgamari/monoidal-containers#76]
This is a blocker for #74.

It would allow us to drop the conditional IsList instances.

**Comment by fumieval** [comment]
@ali-abrar Are you maintaining this package?

**Comment by emilypi** [comment]
I'd like to figure out what we need for this package too. Afaict, @bgamari is the most (only?) active maintainer. He's easy to find.

**Comment by ali-abrar** [comment]
#86 will drop support for ghc<8.

**Comment by fumieval** [comment]
thank you
