### ISSUE TITLE
Relax upper bound: lens

### ISSUE THREAD

**Issue by endgame** [bgamari/monoidal-containers#78]
Notwithstanding potential changes in #73 and #75, I am using `allow-newer: monoidal-containers:aeson,lens` in my `cabal.project` to allow `lens-5` in my project, and it seems to be working fine. Can you please consider relaxing the upper bound and publishing releases/revisions as appropriate?

**Comment by newhoggy** [comment]
Please update and publish a new revision.  Thanks!

**Comment by bgamari** [comment]
Done.

**Comment by endgame** [comment]
https://hackage.haskell.org/package/monoidal-containers-0.6.0.1 still says `lens >=4.4 && <5`, as does the cabal file on `master`. Am I missing something?

https://github.com/bgamari/monoidal-containers/blob/64c44462f8fed152e6fe56d375be97c80d874fd4/monoidal-containers.cabal#L55
