### ISSUE TITLE
Offer to help maintain

### ISSUE THREAD

**Issue by ocharles** [bgamari/monoidal-containers#93]
Hi, I would like to offer to help maintain this package. I would like to help with routine fixes like version bounds bumps and releasing to Hackage. If you're interested, could I get commit rights here and a maintainer bit on Hackage? I'm `OliverCharles` there.

**Comment by bgamari** [comment]
Hi @ocharles, thank you very much for the offer which I warmly accept. You should now find that you have push permissions here and Hackage.

**Comment by ocharles** [comment]
Thanks!
