### ISSUE TITLE
MonoidalMap.fromList does not append values for duplicate keys

### ISSUE THREAD

**Issue by Tristano8** [bgamari/monoidal-containers#94]
For example:

```
-- >>> let map = MonoidalMap.fromList [("a", [1]), ("b", [2]), ("a", [3])]
-- >>> print map
-- MonoidalMap {getMonoidalMap = fromList [("a",[3]),("b",[2])]}
```

Compared with:

```
-- >>> let map = MonoidalMap.fromListWith (<>) [("a", [1]), ("b", [2]), ("a", [3])]
-- >>> print map
-- MonoidalMap {getMonoidalMap = fromList [("a",[3,1]),("b",[2])]}
```

I think the latter should be the default behaviour. If you're reaching for a `MonoidalMap` I don't imagine you'd want the dropping of values from duplicate keys

**Comment by ocharles** [comment]
I agree. I think that `fromList` should be observationally equal to `foldMap (uncurry singleton)`

**Comment by ocharles** [comment]
Aha. In that case this looks like it's a wontfix, sorry.
